/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../common";
import type {
  ReputationManager,
  ReputationManagerInterface,
} from "../ReputationManager";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "user",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "newReputation",
        type: "uint256",
      },
    ],
    name: "ReputationUpdated",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_user",
        type: "address",
      },
    ],
    name: "decreaseReputation",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_user",
        type: "address",
      },
    ],
    name: "increaseReputation",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "reputation",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x60808060405234601557610223908161001b8239f35b600080fdfe608080604052600436101561001357600080fd5b60003560e01c9081634f76dc6114610171575080638651fc51146100835763b9f794511461004057600080fd5b3461007e57602036600319011261007e576004356001600160a01b0381169081900361007e5760005260006020526020604060002054604051908152f35b600080fd5b3461007e57602036600319011261007e576004356001600160a01b0381169081900361007e578060005260006020526040600020541561012c578060005260006020526040600020805490600019820191821161011657558060005260006020527ffc577563f1b9a0461e24abef1e1fcc0d33d3d881f20b5df6dda59de4aae2c8216020604060002054604051908152a2005b634e487b7160e01b600052601160045260246000fd5b60405162461bcd60e51b815260206004820152601d60248201527f52657075746174696f6e2063616e6e6f74206265206e656761746976650000006044820152606490fd5b3461007e57602036600319011261007e576004356001600160a01b038116919082900361007e57816000526000602052604060002080549160018301809311610116577ffc577563f1b9a0461e24abef1e1fcc0d33d3d881f20b5df6dda59de4aae2c821926020925583600052600082526040600020548152a200fea2646970667358221220c8e4969961143713ac78c8c27ffce1f9937b0c0b2aac616cf2f93e1ff6ccdc0e64736f6c634300081a0033";

type ReputationManagerConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: ReputationManagerConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class ReputationManager__factory extends ContractFactory {
  constructor(...args: ReputationManagerConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      ReputationManager & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): ReputationManager__factory {
    return super.connect(runner) as ReputationManager__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): ReputationManagerInterface {
    return new Interface(_abi) as ReputationManagerInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ReputationManager {
    return new Contract(address, _abi, runner) as unknown as ReputationManager;
  }
}
